image:
  repository: ghcr.io/noi-techpark/opendatahub-public-transport/dc-feed-fetcher
  pullPolicy: IfNotPresent
  tag: "0.1.0"

env:
  CONFIG_PATH: "/config/feed-config.yaml"
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri

configMap:
  mountPath: "/config/"
  files: {}
