# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

feeds:
  - endpoint: "https://efa.sta.bz.it/siri-lite/vehicle-monitoring"
    provider: "pt-feed/sta-siri-lite-vehicle-monitoring"
    cron: "0/30 * * * * *"
    format: "json"
    protocol: "siri-lite"
    metadata:
      agency: "sta"
      feed_type: "vehicle-monitoring"
    headers:
      Accept: "application/json"

  # - endpoint: "https://efa.sta.bz.it/siri-lite/estimated-timetable"
  #   provider: "pt-feed/sta-siri-lite-estimated-timetable"
  #   cron: "0/30 * * * * *"
  #   format: "json"
  #   protocol: "siri-lite"
  #   metadata:
  #     agency: "sta"
  #     feed_type: "estimated-timetable"
  #   headers:
  #     Accept: "application/json"

  - endpoint: "https://efa.sta.bz.it/siri-lite/situation-exchange"
    provider: "pt-feed/sta-siri-lite-situation-exchange"
    cron: "0/30 * * * * *"
    format: "json"
    protocol: "siri-lite"
    metadata:
      agency: "sta"
      feed_type: "situation-exchange"
    headers:
      Accept: "application/json"